### ISSUE TITLE
TypeError: cannot unpack non-iterable int object

### ISSUE THREAD

**Issue by shantanuo** [autofitcloud/isitfit#1]
Getting an error:

(

> base) root@080ae74773e0:/# isitfit
> Calculating the Cost-Weighted Average Utilization (CWAU) of the AWS EC2 account:
> Fetching history...
> Cloudtrail page 1: 1it [00:00,  1.24it/s]
> Cloudtrail page 1: 1it [00:00,  5.10it/s]
> First pass, EC2 instance: 1it [00:00, ?it/s]
> Second pass, EC2 instance: 1it [00:00, ?it/s]
> Traceback (most recent call last):
>   File "/opt/conda/bin/isitfit", line 10, in <module>
>     sys.exit(cli())
>   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/isitfit/cli.py", line 26, in cli
>     n_ec2, sum_capacity, sum_used, cwau = mm.get_ifi()
> TypeError: cannot unpack non-iterable int object
>

**Comment by shadiakiki1986** [comment]
Thanks for your bug report. Indeed this seems to happen when the tool doesn't manage to pick up any cloudwatch data at all. I made a few commits to clarify the logged output, showing which instances don't have any data, and fixing the issue you had. Let me know if this works for you now.

**Comment by shadiakiki1986** [comment]
By the way, you'll need to update to version 0.1.4 for the fixes: `pip3 install --upgrade isitfit`

**Comment by shantanuo** [comment]
I can now get it working for ap-south-1 region. But us-east-1 region is still failing. This is very strange.

> (base) root@080ae74773e0:/#  isitfit
> Is it fit?
> Cost-Weighted Average Utilization (CWAU) of the AWS EC2 account:
> Fetching history...
> Cloudtrail page 1: 1it [00:00,  1.27it/s]
> Cloudtrail page 1: 1it [00:00,  5.15it/s]
> First pass through EC2 instances: 1it [00:00, ?it/s]
> Second pass through EC2 instances: 1it [00:00, ?it/s]
> ... done
> 
> Summary:
> 
> Field                       Value
> --------------------------  ----------
> Analysis start date         2019-06-12
> Analysis end date           2019-09-10
> Number of EC2 machines      0
> Billed cost                 0.00 $
> Used cost                   0.00 $
> CWAU = Used / Billed * 100  0 %
> 
> For reference:
> * CWAU >= 70% is well optimized
> * CWAU <= 30% is underused
> * isitfit version 0.1.4 is based on CPU utilization only (and not yet on memory utilization)

## Change region, and it fails....

> (base) root@080ae74773e0:/#  isitfit
> Is it fit?
> Cost-Weighted Average Utilization (CWAU) of the AWS EC2 account:
> Fetching history...
> Cloudtrail page 1: 0it [00:00, ?it/s]
> Traceback (most recent call last):
>   File "/opt/conda/bin/isitfit", line 10, in <module>
>     sys.exit(cli())
>   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/isitfit/cli.py", line 35, in cli
>     n_ec2, sum_capacity, sum_used, cwau = mm.get_ifi()
>   File "/opt/conda/lib/python3.7/site-packages/isitfit/mainManager.py", line 45, in get_ifi
>     self.cloudtrail_manager.init_data(self.ec2_resource.instances.all(), n_ec2)
>   File "/opt/conda/lib/python3.7/site-packages/isitfit/cloudtrail_ec2type.py", line 18, in init_data
>     self.df_cloudtrail = self._fetch()
>   File "/opt/conda/lib/python3.7/site-packages/isitfit/cloudtrail_ec2type.py", line 33, in _fetch
>     df = cloudtrail_manager.ec2_typeChanges()
>   File "/opt/conda/lib/python3.7/site-packages/gitRemoteAws/pull_cloudtrail_lookupEvents.py", line 165, in ec2_typeChanges
>     r_run = man2_run.handleIterator(iterator_run)
>   File "/opt/conda/lib/python3.7/site-packages/gitRemoteAws/pull_cloudtrail_lookupEvents.py", line 85, in handleIterator
>     result = self._handleEventAny(event)
>   File "/opt/conda/lib/python3.7/site-packages/gitRemoteAws/pull_cloudtrail_lookupEvents.py", line 94, in _handleEventAny
>     return self._handleEventRun(event)
>   File "/opt/conda/lib/python3.7/site-packages/gitRemoteAws/pull_cloudtrail_lookupEvents.py", line 106, in _handleEventRun
>     instanceId = [x for x in event['Resources'] if x['ResourceType']=='AWS::EC2::Instance'][0]['ResourceName']
> IndexError: list index out of range
>

**Comment by shadiakiki1986** [comment]
It seems that I have a bug for the case of regions with no ec2 instances.
Is this indeed the case of your account in us-east-1?

**Comment by shadiakiki1986** [comment]
The new version 0.1.5 deals with the case of no ec2 instances found. You can install it with `pip3 install --upgrade isitfit`

**Comment by shadiakiki1986** [comment]
Hello @shantanuo  It's been a few months since you first tried out isitfit. Since then, I've improved it a lot and it's at version 0.20 now. I'll be happy to get your feedback on the latest version. You could upgrade with `pip3 install --upgrade isitfit` and then run `isitfit cost analyze` to calculate the efficiency of your AWS account, followed by `isitfit cost optimize` to get recommendations on which EC2/RDS sizes better be changed. Have a nice day!

**Comment by shantanuo** [comment]
Getting an error:

```
(base) root@080ae74773e0:/# isitfit cost analyze
Profiles in AWS credential file:
- default

(use `AWS_PROFILE=myprofile isitfit ...` or `isitfit command --profile=myprofile ...` to skip this prompt)
Profile to use [default]:
Number of days to lookback (between 1 and 90, use `isitfit cost --ndays=7 ...` to skip this prompt) [7]:
Traceback (most recent call last):
  File "/opt/conda/bin/isitfit", line 10, in <module>
    sys.exit(cli_core())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/isitfit/cli/click_descendents.py", line 40, in invoke
    ret = super().invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/isitfit/cli/click_descendents.py", line 40, in invoke
    ret = super().invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/isitfit/cli/click_descendents.py", line 58, in invoke
    ret = super().invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/isitfit/cli/cost.py", line 59, in analyze
    mm_eca = ec2_cost_analyze(ctx, filter_tags, save_details)
  File "/opt/conda/lib/python3.7/site-packages/isitfit/cost/ec2_analyze.py", line 578, in pipeline_factory
    ec2_cat = Ec2Catalog()
TypeError: __init__() missing 1 required positional argument: 'allow_ec2_different_family'

```

Optimize command works as expected!

```
(base) root@080ae74773e0:/# isitfit cost optimize
Profiles in AWS credential file:
- default

(use `AWS_PROFILE=myprofile isitfit ...` or `isitfit command --profile=myprofile ...` to skip this prompt)
Profile to use [default]:
Number of days to lookback (between 1 and 90, use `isitfit cost --ndays=7 ...` to skip this prompt) [7]:
Allow suggesting EC2 instance types of different families? m2.4xlarge -> r4.2xlarge [y/N]: N
EC2 instances, counting in all regions            : 100%|███████████████████████████████████████████████████████████████████████████████| 18/18 [00:11<00:00,  2.34it/s]
No resources found in EC2 instances
Redshift clusters, counting in all regions        : 100%|███████████████████████████████████████████████████████████████████████████████| 18/18 [00:10<00:00,  2.30it/s]
No resources found in Redshift clusters
No optimizations from EC2

No optimizations from redshift

⛅ Generated by isitfit version 0.20.1

Useful links:
ℹ️  isitfit homepage         https://isitfit.autofitcloud.com
� isitfit issues           https://github.com/autofitcloud/isitfit/issues
� Global Climate Strike    https://twitter.com/hashtag/ClimateStrike
❤️  Built by AutofitCloud    https://www.autofitcloud.com


```

**Comment by shadiakiki1986** [comment]
Thanks! Issue fixed in version 0.20.2. Just upgrade with `pip3 install --upgrade isitfit` and try again `isitfit cost analyze`

**Comment by shantanuo** [comment]
Thanks for your quick response. It is working as expected. Does it cost anything to run the command?

```
(base) root@080ae74773e0:/# isitfit cost analyze
Profiles in AWS credential file:
- default

(use `AWS_PROFILE=myprofile isitfit ...` or `isitfit command --profile=myprofile ...` to skip this prompt)
Profile to use [default]:
Number of days to lookback (between 1 and 90, use `isitfit cost --ndays=7 ...` to skip this prompt) [7]:

EC2 instances, counting in all regions            : 100%|███████████████████████████████████████████████████████████████████████████████| 18/18 [00:11<00:00,  2.32it/s]
No resources found in EC2 instances
Redshift clusters, counting in all regions        : 100%|███████████████████████████████████████████████████████████████████████████████| 18/18 [00:10<00:00,  2.20it/s]
No resources found in Redshift clusters
Error: No data found
If the problem persists, please report it at https://github.com/autofitcloud/isitfit/issues/new

```
Appreciate your efforts and this open source code!

**Comment by shadiakiki1986** [comment]
> Does it cost anything to run the command?

The only cost is the AWS cloudwatch metric download, which costs around 30 cents per 2000 EC2 hosts ([reference](https://aws.amazon.com/cloudwatch/pricing/)).

**Comment by shadiakiki1986** [comment]
I see from your test results that you test isitfit on an empty AWS account. Do you also use it on another non-empty account? I'm looking for feedback to see the impact of `isitfit` in the community.

**Comment by shantanuo** [comment]
Sure. Here we go...
https://gist.github.com/shantanuo/20045457d6cefcd42caf2466fb2d369a

By the way, I tried to write a similar module:
https://github.com/shantanuo/easyboto

**Comment by shadiakiki1986** [comment]
Thanks! What are your plans for `easyboto`? Is it in use in production?
