### ISSUE TITLE
Unable to run isitfit after installation

### ISSUE THREAD

**Issue by CoreyMcDonald** [autofitcloud/isitfit#2]
`ModuleNotFoundError: No module named 'gitRemoteAws' `
 
after running isitfit --version post installation

**Comment by shadiakiki1986** [comment]
Thanks.  Fixed in version 0.2.3. You can upgrade with `pip3 install --upgrade isitfit`. Let me know if this works.

**Comment by shadiakiki1986** [comment]
This issue seems to be fixed now, so I'll close it. Let me know if you still face any issues.
